" 禁用內置插件
let g:loaded_gzip=1
let g:loaded_tar=1
let g:loaded_tarPlugin=1
let g:loaded_zip=1
let g:loaded_zipPlugin=1
let g:loaded_getscript=1 
let g:loaded_getscriptPlugin=1
let g:loaded_vimball=1
let g:loaded_vimballPlugin=1
let g:loaded_2html_plugin=1
let g:loaded_logiPat=1
let g:loaded_rrhelper=1
let g:loaded_netrw=1
let g:loaded_netrwPlugin=1
let g:loaded_netrwSettings=1
let g:loaded_netrwFileHandlers=1
" let g:loaded_matchit=1
" let g:loaded_matchparen=1

" 不與vi兼容
set nocompatible

" 終端顏色與深色背景
set termguicolors
set background=dark

" 使用系統剪貼板
set clipboard^=unnamed,unnamedplus

" 行號與相對行號
set number
set relativenumber

" 語法高亮開啟
syntax on

" 插件及縮進根據文件類型開啟
filetype plugin indent on

" 在80行設置一條線
set colorcolumn=80

" 高亮光標所在的行列
set cursorline
set cursorcolumn

" 超時功能檢測
set timeout
set timeoutlen=200
set ttimeout
set ttimeoutlen=100

" 自動縮進
set autoindent

" 開啟c/c++縮進優化
set cindent

" 設定1 TAB = 2 Space
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" UI
set scrolloff=1
set sidescroll=1
set laststatus=2
set showtabline=2

" 顯示匹配的括號
set showmatch
set matchtime=2

" 顯示最後一行
set display=lastline

" 延遲繪製以提升性能
set lazyredraw

" 顯示光標所在的坐標
set ruler

" 切分視窗總是在右邊與下面
set splitright
set splitbelow

" 關閉自動摺行
set nowrap

" 高亮搜索內容
set hlsearch

" 增量搜索結果
set incsearch

" 搜索忽略大小寫
set ignorecase

" 預設忽略大小寫，除非搜索的文字中含有大寫字母
set smartcase

" 禁用備份文件、交換文件、undo文件
set nobackup
set noswapfile
set noundofile

" 當文件在其他地方被編輯，vim自動重新讀取 
set autoread

" wildmenu
set wildmenu
set wildmode=longest:list,full

" 右下角顯示命令
set showcmd

" 設定Backspace模式
set backspace=eol,start,indent

" Leader and Local Leader
let mapleader=" "
let maplocalleader=","

" 用jk代替Esc
inoremap jk <Esc>

" 快速切換視窗
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" 根據文件類型微調設定
augroup FileTypeSetup

  " 清除同組的歷史自動命令
  autocmd!

  " c/c++使用//當作註釋
  autocmd FileType c,cpp setlocal commentstring=//\ %s

  " quickfix隱藏行號
  autocmd FileType qf setlocal nonumber

augroup END

" 安裝插件管理器vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs 
        \ https://raw.github.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
nnoremap <leader>pl <Cmd>PlugInstall<CR>

" 安裝插件 
call plug#begin('~/.vim/plugged')
Plug 'easymotion/vim-easymotion'
Plug 'tpope/vim-commentary'
Plug 'andymass/vim-matchup'
Plug 'rhysd/clever-f.vim'
Plug 'Yggdroot/indentLine', {'on': []} 
Plug 'machakann/vim-highlightedyank', {'on': []}
Plug 'airblade/vim-gitgutter', {'on': []}
Plug 'ryanoasis/vim-devicons', {'on': []}
Plug 'chrisbra/Colorizer', {'on': []}
Plug 'morhetz/gruvbox', {'on': []}
Plug 'raimondi/delimitMate', {'on': []}
Plug 'luochen1990/rainbow', {'on': []}
Plug 'itchyny/lightline.vim', {'on': []}
Plug 'dyng/ctrlsf.vim', {'on': []}
Plug 'dense-analysis/ale', {'on': []}
Plug 'junegunn/fzf', {'do': { -> fzf#install() }}
Plug 'preservim/nerdtree', {'on': ['NERDTreeToggle']}
Plug 'voldikss/vim-floaterm', {'on': ['FloatermToggle', 'FloatermNew']}
Plug 'junegunn/fzf.vim', {'on': ['Files', 'Buffers', 'Rg', 'Lines', 'BLines']}
Plug 'liuchengxu/vim-which-key', {'on': ['WhichKey', 'WhichKey!']}
Plug 'lambdalisue/suda.vim', {'on': ['SudaRead', 'SudaWrite']}
Plug 'liuchengxu/vista.vim', {'on': ['Vista']}
Plug 'octol/vim-cpp-enhanced-highlight', {'for': ['c', 'cpp']}
Plug 'vim-python/python-syntax', {'for': ['python']}
Plug 'tbastos/vim-lua', {'for': 'lua'}
call plug#end()

" 根據事件、文件類型延遲加載插件
augroup buf_read_post
  autocmd!
  autocmd BufReadPost * call plug#load('gruvbox', 'rainbow', 'lightline.vim', 
        \'Colorizer', 'ale', 'vim-devicons', 'vim-gitgutter', 'vim-highlightedyank',
        \'indentLine')
        \| autocmd! buf_read_post
        \| colorscheme gruvbox
        \| call rainbow_main#load()
        \| let g:lightline={'colorscheme': 'apprentice'}
        \| call lightline#enable()
        \| call Colorizer#ColorToggle()
        \| call gitgutter#enable()
augroup END

augroup insert_enter
  autocmd!
  autocmd InsertEnter * call plug#load('delimitMate')
        \| autocmd! insert_enter
augroup END

augroup cmdline_enter
  autocmd!
  autocmd CmdlineEnter * call plug#load('ctrlsf.vim')
        \| autocmd! cmdline_enter
augroup END

" vim-which-key
nnoremap <silent> <leader> :<c-u>WhichKey '<Space>'<CR>
nnoremap <silent> <localleader> :<c-u>WhichKey ','<CR>

" fzf.vim
nnoremap <leader>fb <Cmd>Buffers<CR>
nnoremap <leader>ff <Cmd>Files ~/<CR>
nnoremap <leader>fF <Cmd>Files<CR>
nnoremap <leader>fs <Cmd>Lines<CR>
nnoremap <leader>fS <Cmd>BLines<CR>
nnoremap <leader>fw <Cmd>Rg<CR>

" vim-floaterm
nnoremap <silent> <leader>tt :FloatermNew --width=0.9 --height=0.88<CR>
tnoremap <silent> <leader>tt <C-\><C-n>:FloatermNew<CR>
nnoremap <silent> <leader>tp :FloatermPrev<CR>
tnoremap <silent> <leader>tp <C-\><C-n>:FloatermPrev<CR>
nnoremap <silent> <leader>tn :FloatermNext<CR>
tnoremap <silent> <leader>tn <C-\><C-n>:FloatermNext<CR>
nnoremap <silent> <leader>tT :FloatermToggle<CR>
tnoremap <silent> <leader>tT <C-\><C-n>:FloatermToggle<CR>

" NerdTree
let NERDTreeShowHidden=1
nnoremap <leader>pn <Cmd>NERDTreeToggle<CR>

" vista.vim
nnoremap <leader>lo <Cmd>Vista<CR>
