" {{{ Disable Distributed Plugins }}}
let g:loaded_gzip=1
let g:loaded_tar=1
let g:loaded_tarPlugin=1
let g:loaded_zip=1
let g:loaded_zipPlugin=1
let g:loaded_getscript=1 
let g:loaded_getscriptPlugin=1
let g:loaded_vimball=1
let g:loaded_vimballPlugin=1
let g:loaded_2html_plugin=1
let g:loaded_logiPat=1
let g:loaded_rrhelper=1
let g:loaded_netrw=1
let g:loaded_netrwPlugin=1
let g:loaded_netrwSettings=1
let g:loaded_netrwFileHandlers=1
" let g:loaded_matchit=1
" let g:loaded_matchparen=1

" {{{ Disabled bell sound }}} 
set noeb
set vb t_vb=

" {{{ Do not compat with vi }}}
set nocompatible

" {{{ Terminal color and background }}}
set termguicolors
set background=dark

" {{{ Clipboard }}}
set clipboard^=unnamed,unnamedplus

" {{{ Line Number }}}
set number
set relativenumber

" {{{ Language Syntax Highlight }}}
syntax on

" {{{ Turn on indent and plulgin with specific filetype }}}
filetype plugin indent on

" {{{ Wrap Automatically }}}
set whichwrap=h,l,<,>,[,],~

" {{{ Show a vertical line at 80 coloumn }}}
set colorcolumn=80

" {{{ Highlight the current column and line }}}
set cursorline
set cursorcolumn

" {{{ Timeout }}}
set timeout
set timeoutlen=200
set ttimeout
set ttimeoutlen=100

" {{{ Indent }}}
set autoindent
set cindent

" {{{ TAB Setting }}}
set expandtab
set softtabstop=2
set tabstop=2
set shiftwidth=2

" {{{ UI }}}
set scrolloff=1
set sidescroll=1
set laststatus=2
set showtabline=2
set pumheight=12
set pumwidth=20

" {{{ Show matched bracket }}}
set showmatch
set matchtime=2

" {{{ Show the last line }}}
set display=lastline

" {{{ Lasy Draw to Improve efficiency }}}
set lazyredraw

" {{{ Show Coordinate of Cursor }}}
set ruler

" {{{ Split window on right and below }}}
set splitright
set splitbelow

" {{{ Turn off auto-wrap }}}
set nowrap

" {{{ Searching }}}
set hlsearch
set incsearch
set ignorecase
set smartcase

" {{{ Disable backup, swap, unco file }}}
set nobackup
set noswapfile
set noundofile

" {{{ Revert file automatically }}}
set autoread

" {{{ Wild Menu }}}
set wildmenu
set wildmode=longest:list,full

" {{{ Show Command }}}
set showcmd

" {{{ Backspace }}}
set backspace=eol,start,indent

" {{{ Leader Key }}}
let mapleader="\<Space>"
let maplocalleader=","

" {{{ ESC Mapping }}}
inoremap jk <Esc>

" {{{ Change window key }}}
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" {{{ Setup for specific filetype }}}
augroup FileTypeSetup

  " 清除同組的歷史自動命令
  autocmd!

  " c/c++使用//當作註釋
  autocmd FileType c,cpp setlocal commentstring=//\ %s

  " python使用4個空白當作縮進
  autocmd FileType python setlocal tabstop=4 shiftwidth=4

  " quickfix隱藏行號
  autocmd FileType qf setlocal nonumber

augroup END

" {{{ Installing Plugin Manager - vim-plug }}}
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs 
        \ https://raw.github.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
nnoremap <leader>tl <Cmd>PlugInstall<CR>

" {{{ Installing Plugins }}}
call plug#begin('~/.vim/plugged')
Plug 'easymotion/vim-easymotion'
Plug 'tpope/vim-commentary'
Plug 'andymass/vim-matchup'
Plug 'rhysd/clever-f.vim'
Plug 'Yggdroot/indentLine', {'on': []} 
Plug 'machakann/vim-highlightedyank', {'on': []}
Plug 'airblade/vim-gitgutter', {'on': []}
Plug 'ryanoasis/vim-devicons', {'on': []}
Plug 'chrisbra/Colorizer', {'on': []}
Plug 'morhetz/gruvbox', {'on': []}
Plug 'jiangmiao/auto-pairs', {'on': []}
Plug 'luochen1990/rainbow', {'on': []}
Plug 'itchyny/lightline.vim', {'on': []}
Plug 'dyng/ctrlsf.vim', {'on': []}
Plug 'dense-analysis/ale', {'on': []}
Plug 'puremourning/vimspector', {'on': []}
Plug 'junegunn/fzf', {'do': { -> fzf#install() }}
Plug 'preservim/nerdtree', {'on': ['NERDTreeToggle']}
Plug 'voldikss/vim-floaterm', {'on': ['FloatermToggle', 'FloatermNew']}
Plug 'junegunn/fzf.vim', {'on': ['Files', 'Buffers', 'Rg', 'Lines', 'BLines']}
Plug 'liuchengxu/vim-which-key', {'on': ['WhichKey', 'WhichKey!']}
Plug 'lambdalisue/suda.vim', {'on': ['SudaRead', 'SudaWrite']}
Plug 'liuchengxu/vista.vim', {'on': ['Vista']}
Plug 'octol/vim-cpp-enhanced-highlight', {'for': ['c', 'cpp']}
Plug 'vim-python/python-syntax', {'for': ['python']}
Plug 'tbastos/vim-lua', {'for': 'lua'}
Plug 'prabirshrestha/asyncomplete.vim', {'on': []}
Plug 'prabirshrestha/asyncomplete-lsp.vim', {'on': []}
Plug 'prabirshrestha/asyncomplete-buffer.vim', {'on': []}
Plug 'prabirshrestha/asyncomplete-file.vim', {'on': []}
Plug 'prabirshrestha/vim-lsp', {'on': []}
Plug 'mattn/vim-lsp-settings', {'on': []}
call plug#end()

" {{{ Lazy Loading }}}
augroup buf_read_post
  autocmd!
  autocmd BufReadPost * call plug#load('gruvbox', 'lightline.vim', 
        \'Colorizer', 'ale', 'vim-devicons', 'vim-gitgutter', 'vim-highlightedyank',
        \'vimspector', 'indentLine')
        \| autocmd! buf_read_post
        \| colorscheme gruvbox
        \| call lightline#enable()
        \| call Colorizer#ColorToggle()
        \| call gitgutter#enable()
        \| let g:indentLine_char='c'
        \| let g:indentLine_char_list=['|', '¦', '┆', '┊']
        \| IndentLinesEnable
augroup END

augroup insert_enter
  autocmd!
  autocmd InsertEnter * call plug#load('auto-pairs', 'rainbow')
        \| autocmd! insert_enter
        \| call AutoPairsTryInit()
        \| if has_key(g:AutoPairs, '"')
        \| let b:AutoPairs = copy(g:AutoPairs)
        \| call remove(b:AutoPairs, '"')
        \| endif
augroup END

augroup cmdline_enter
  autocmd!
  autocmd CmdlineEnter * call plug#load('ctrlsf.vim')
        \| autocmd! cmdline_enter
augroup END

" {{{ UI }}}
" rainbow
let g:rainbow_active=1

" {{{ TOOL }}}
" vim-which-key
nnoremap <silent> <leader> :<c-u>WhichKey '<Space>'<CR>
nnoremap <silent> <localleader> :<c-u>WhichKey ','<CR>

" fzf.vim
nnoremap <leader>fb <Cmd>Buffers<CR>
nnoremap <leader>ff <Cmd>Files ~/<CR>
nnoremap <leader>fF <Cmd>Files<CR>
nnoremap <leader>fs <Cmd>Lines<CR>
nnoremap <leader>fS <Cmd>BLines<CR>
nnoremap <leader>fw <Cmd>Rg<CR>

" vim-floaterm
nnoremap <silent> <leader>tf :FloatermNew --width=0.9 --height=0.88<CR>
tnoremap <silent> <leader>tf <C-\><C-n>:FloatermNew<CR>
nnoremap <silent> <leader>tp :FloatermPrev<CR>
tnoremap <silent> <leader>tp <C-\><C-n>:FloatermPrev<CR>
nnoremap <silent> <leader>tN :FloatermNext<CR>
tnoremap <silent> <leader>tN <C-\><C-n>:FloatermNext<CR>
nnoremap <silent> <leader>tT :FloatermToggle<CR>
tnoremap <silent> <leader>tT <C-\><C-n>:FloatermToggle<CR>

" NerdTree
let NERDTreeShowHidden=1
nnoremap <leader>tn <Cmd>NERDTreeToggle<CR>

" vista.vim
nnoremap <leader>lo <Cmd>Vista<CR>

" vim-easymotion
map <Leader>L <Plug>(easymotion-bd-jk)
map <Leader>W <Plug>(easymotion-bd-w)

" {{{ DAP }}}
" vimspector
let g:vimspector_enable_mappings = 'HUMAN'

" {{{ LSP }}}
" asyncomplete.vim/asyncomplete-file.vim/asyncomplete-buffer.vim/asyncomplete-lsp.vim/vim-lsp/vim-lsp-settings
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? asyncomplete#close_popup() : "\<cr>"

function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes
  if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
  nmap <buffer> gd <plug>(lsp-definition)
  nmap <buffer> gs <plug>(lsp-document-symbol-search)
  nmap <buffer> gS <plug>(lsp-workspace-symbol-search)
  nmap <buffer> gr <plug>(lsp-references)
  nmap <buffer> gi <plug>(lsp-implementation)
  nmap <buffer> gt <plug>(lsp-type-definition)
  nmap <buffer> <leader>rn <plug>(lsp-rename)
  nmap <buffer> [g <plug>(lsp-previous-diagnostic)
  nmap <buffer> ]g <plug>(lsp-next-diagnostic)
  nmap <buffer> K <plug>(lsp-hover)
  nnoremap <buffer> <expr><c-f> lsp#scroll(+4)
  nnoremap <buffer> <expr><c-d> lsp#scroll(-4)
  let g:lsp_format_sync_timeout = 1000
  autocmd! BufWritePre *.rs,*.go call execute('LspDocumentFormatSync')
endfunction

augroup lsp_install
  au!
  " call s:on_lsp_buffer_enabled only for languages that has the server registered.
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

augroup start_lsp
  autocmd!
  autocmd InsertEnter * call plug#load('asyncomplete.vim', 'asyncomplete-file.vim',
        \'asyncomplete-buffer.vim', 'asyncomplete-lsp.vim', 'vim-lsp', 'vim-lsp-settings')
        \| autocmd! start_lsp
        \| call asyncomplete#enable_for_buffer()
        \| call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({'name': 'file', 'allowlist': ['*'], 'priority': 10, 'completor': function('asyncomplete#sources#file#completor')}))
        \| call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({'name': 'buffer', 'allowlist': ['*'], 'blocklist': ['go'], 'completor': function('asyncomplete#sources#buffer#completor'), 'config': {'max_buffer_size': 5000000}}))
        \| call lsp#enable()
        \| au User lsp_setup call lsp#register_server({'name': 'clangd', 'cmd': {server_info->['clangd', '-background-index']}, 'whitelist': ['c', 'cpp', 'objc', 'objcpp']})
        \| au User lsp_setup call lsp#register_server({'name': 'pyls', 'cmd': {server_info->['pyls']}, 'whitelist': ['python']})
augroup END
