general.import = []
working_directory = "None"
general.live_config_reload = true
general.ipc_socket = true

[env]

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 8, y = 8 }
dynamic_padding = false
decorations = "Full"
opacity = 0.9
blur = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments = false
option_as_alt = "None"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Semibold" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12.00
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#d8d8d8"
background = "#181818"
dim_foreground = "#828482"
bright_foreground = "#d8d8d8"

[colors.cursor]
text = "CellBackground" 
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "CellBackground" 
cursor = "CellForeground"

[colors.search.matches]
foreground = "#181818"
background = "#ac4242"

[colors.search.focused_match]
foreground = "#181818"
background = "#f4bf75"

[colors.hints.start]
foreground = "#181818"
background = "#f4bf75"

[colors.hints.end]
foreground = "#181818"
background = "#ac4242"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#181818"
background = "#d8d8d8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#181818"
red = "#ac4242"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"

[colors.bright]
black = "#6b6b6b"
red = "#c55555"
green = "#aac474"
yellow = "#feca88"
blue = "#82b8c8"
magenta = "#c28cb8"
cyan = "#93d3c3"
white = "#f8f8f8"

[colors.dim]
black = "#0f0f0f"
red = "#712b2b"
green = "#5f6f3a"
yellow = "#a17e4d"
blue = "#456877"
magenta = "#704d68"
cyan = "#4d7770"
white = "#8e8e8e"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

[bell]
animation = "EaseOutCubic"
duration = 1
color = "#d8d8d8"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = "None"
blink_interval = 500
blink_timeout = 5
unfocused_hollow = true
thickness = 0.0

[terminal]
osc52 = "CopyPaste"
shell = { program = "/bin/bash", args = ["-l"] }

[mouse]
hide_when_typing = true
bindings = []

[hints]
alphabet = "jfkdls;ahgurieowpq"

[keyboard]
bindings = []
