local config = {
  flavour = 'mocha',
  background = { light = 'latte', dark = 'mocha' },
  dim_inactive = {
    enabled = false,
    shade = 'dark',
    percentage = 0.2,
  },
  transparent_background = false,
  show_end_of_buffer = false,
  term_colors = true,
  compile_path = vim.fn.stdpath('cache') .. '/catppuccin',
  styles = {
    comments = {},
    properties = {},
    functions = { 'bold' },
    keywords = {},
    operators = { 'bold' },
    conditionals = { 'bold' },
    loops = { 'bold' },
    booleans = { 'bold' },
    numbers = {},
    types = {},
    strings = {},
    variables = {},
  },
  integrations = {
    treesitter = true,
    native_lsp = {
      enabled = true,
      virtual_text = {
        errors = {},
        hints = {},
        warnings = {},
        information = {},
      },
      underlines = {
        errors = { 'underline' },
        hints = { 'underline' },
        warnings = { 'underline' },
        information = { 'underline' },
      },
    },
    aerial = false,
    alpha = false,
    barbar = false,
    beacon = false,
    cmp = true,
    coc_nvim = false,
    dap = { enabled = true, enable_ui = true },
    dashboard = false,
    dropbar = { enabled = true, color_mode = true },
    fern = false,
    fidget = true,
    flash = false,
    gitgutter = false,
    gitsigns = true,
    harpoon = false,
    headlines = false,
    hop = true,
    illuminate = true,
    indent_blankline = { enabled = true, colored_indent_levels = false },
    leap = false,
    lightspeed = false,
    lsp_saga = true,
    lsp_trouble = true,
    markdown = true,
    mason = true,
    mini = false,
    navic = { enabled = false },
    neogit = false,
    neotest = false,
    neotree = { enabled = false, show_root = true, transparent_panel = false },
    noice = false,
    notify = true,
    nvimtree = true,
    overseer = false,
    pounce = false,
    rainbow_delimiters = true,
    sandwich = false,
    semantic_tokens = true,
    symbols_outline = true,
    telekasten = false,
    telescope = { enabled = true },
    treesitter_context = true,
    ts_rainbow = false,
    vim_sneak = false,
    vimwiki = false,
    which_key = true,
  },
  color_overrides = {},
  highlight_overrides = {
    all = function(colors)
      return {
        Comment = { fg = colors.overlay0, style = { 'bold', 'italic' } },
        NormalFloat = { fg = colors.text, bg = colors.mantle },
        FloatBorder = { fg = colors.mantle, bg = colors.mantle },
        CursorLineNr = { fg = colors.green, style = { 'bold' } },

        -- cmp
        Pmenu = { fg = colors.overlay2, bg = colors.base },
        PmenuBorder = { fg = colors.text, bg = colors.base },
        PmenuSel = { bg = colors.green, fg = colors.base },
        CmpItemAbbr = { fg = colors.overlay2 },
        CmpItemAbbrMatch = { fg = colors.blue, style = { 'bold' } },
        CmpDoc = { link = 'NormalFloat' },
        CmpDocBorder = { fg = colors.text, bg = colors.mantle },
      }
    end,
  },
}

return function()
  require('catppuccin').setup(config)
  vim.api.nvim_command('colorscheme catppuccin')
end
