local config = {
  flavour = 'mocha',
  background = { light = 'latte', dark = 'mocha' },
  dim_inactive = {
    enabled = true,
    shade = 'dark',
    percentage = 0.2,
  },
  transparent_background = false,
  show_end_of_buffer = false,
  term_colors = true,
  compile_path = vim.fn.stdpath('cache') .. '/catppuccin',
  styles = {
    comments = {},
    properties = {},
    functions = { 'bold' },
    keywords = {},
    operators = { 'bold' },
    conditionals = { 'bold' },
    loops = { 'bold' },
    booleans = { 'bold' },
    numbers = {},
    types = {},
    strings = {},
    variables = {},
  },
  integrations = {
    treesitter = true,
    native_lsp = {
      enabled = true,
      virtual_text = {
        errors = { 'italic' },
        hints = { 'italic' },
        warnings = { 'italic' },
        information = { 'italic' },
      },
      underlines = {
        errors = { 'underline' },
        hints = { 'underline' },
        warnings = { 'underline' },
        information = { 'underline' },
      },
      inlay_hints = {
        background = true,
      },
    },
    aerial = false,
    alpha = false,
    barbar = false,
    barbecure = {
      dim_dirname = false,
      bold_basename = false,
      dim_context = false,
      alt_background = false,
    },
    beacon = false,
    coc_nvim = false,
    cmp = true,
    dashboard = false,
    dap = { enabled = false, enable_ui = true },
    dropbar = { enabled = false, color_mode = false },
    fern = false,
    fidget = false,
    flash = false,
    gitsigns = true,
    gitgutter = false,
    harpoon = false,
    headlines = false,
    hop = true,
    indent_blankline = { enabled = true, colored_indent_levels = true },
    leap = false,
    lightspeed = false,
    illuminate = false,
    lsp_saga = true,
    lsp_trouble = true,
    markdown = false,
    mason = true,
    mini = false,
    navic = { enabled = false },
    neogit = false,
    neotest = false,
    neotree = { enabled = false, show_root = true, transparent_panel = false },
    noice = true,
    notify = true,
    NormalNvim = false,
    notifier = false,
    nvimtree = true,
    overseer = false,
    pounce = false,
    rainbow_delimiters = false,
    sandwich = false,
    semantic_tokens = false,
    symbols_outline = false,
    telekasten = false,
    telescope = { enabled = false, style = 'nvchad' },
    treesitter_context = false,
    ufo = false,
    window_picer = false,
    octo = false,
    ts_rainbow = true,
    ts_rainbow2 = false,
    vim_sneak = false,
    vimwiki = false,
    which_key = true,
  },
  color_overrides = {
    mocha = {
      base = '#11111b',
    },
  },
  highlight_overrides = {
    all = function(colors)
      return {
        NormalFloat = { fg = colors.text, bg = colors.base },
        Comment = { fg = colors.overlay1, style = { 'bold', 'italic' } },
        CursorLineNr = { fg = colors.green, style = { 'bold' } },
        Pmenu = { fg = colors.text, bg = colors.base },
        PmenuSel = { bg = colors.surface0, style = { 'bold' } },
        PmenuBorder = { fg = colors.surface0, bg = colors.base },
        CmpItemAbbr = { fg = colors.text },
        CmpItemAbbrMatch = { fg = colors.text, style = { 'bold' } },
        CmpDoc = { fg = colors.text, bg = colors.mantle },
        CmpDocBorder = { fg = colors.surface0, bg = colors.base },
        NvimTreeNormal = { fg = colors.text, bg = colors.base },
      }
    end,
  },
}
return function()
  require('catppuccin').setup(config)
  vim.api.nvim_command('colorscheme catppuccin')
end
