return function()

  -- sidebar icon
  local diagnostic_icon = {
    Error = '󰅚',
    Warn = '󰀪',
    Info = '',
    Hint = '󰌶',
  }
  for type, sidebar_icon in pairs(diagnostic_icon) do
    local hl = 'DiagnosticSign' .. type
    vim.fn.sign_define(hl, { text = sidebar_icon, texthl = hl })
  end

  require('lspsaga').setup({
    symbol_in_winbar = {
      enable = true,
      hide_keyword = false,
      show_file = true,
      folder_level = 1,
      color_mode = true,
      delay = 100,
    },
    callhierarchy = {
      layout = 'float',
      keys = {
        edit = 'e',
        vsplit = 'v',
        split = 's',
        tabe = 't',
        quit = 'q',
        shuttle = '[]',
        toggle_or_req = 'u',
        close = '<Esc>',
      },
    },
    code_action = {
      num_shortcut = true,
      only_in_cursor = false,
      show_server_name = true,
      extend_gitsigns = false,
      keys = {
        quit = 'q',
        exec = '<CR>',
      },
    },
    diagnostic = {
      show_code_action = true,
      jump_num_shortcut = true,
      max_width = 0.5,
      max_height = 0.6,
      text_hl_follow = true,
      border_follow = true,
      extend_relatedInformation = true,
      show_layout = 'float',
      show_normal_height = 10,
      max_show_width = 0.9,
      max_show_height = 0.6,
      diagnostic_only_current = false,
      keys = {
        exec_action = 'r',
        quit = 'q',
        toggle_or_jump = '<CR>',
        quit_in_show = { 'q', '<Esc>' },
      },
    },
    hover = {
      max_width = 0.5,
      max_height = 0.7,
      open_link = 'gl',
    },
    implement = {
      enable = true,
      sign = true,
      virtual_text = true,
      priority = 100,
    },
    lightbulb = {
      enable = true,
      sign = true,
      virtual_text = true,
      debounce = 10,
      sign_priority = 20,
    },
    rename = {
      in_select = false,
      auto_save = false,
      project_max_width = 0.5,
      project_max_height = 0.5,
      keys = {
        quit = '<C-c>',
        exec = '<CR>',
        select = 'x',
      },
    },
    beacon = {
      enable = true,
      frequency = 8,
    },
    ui = {
      border = 'rounded',
      devicon = true,
      title = true,
      lines = { '┗', '┣', '┃', '━', '┏' },
      expand = '',
      collapse = '',
      imp_sign = '',
      kind = {
        Class = { ' 󰠱 ', 'LspKindClass' },
        Constant = { ' 󰏿 ', 'LspKindConstant' },
        Constructor = { '  ', 'LspKindConstructor' },
        Enum = { '  ', 'LspKindEnum' },
        EnumMember = { '  ', 'LspKindEnumMember' },
        Event = { '  ', 'LspKindEvent' },
        Field = { ' 󰇽 ', 'LspKindField' },
        File = { ' 󰈙 ', 'LspKindFile' },
        Function = { ' 󰊕 ', 'LspKindFunction' },
        Interface = { '  ', 'LspKindInterface' },
        Key = { ' 󰌋 ', 'LspKindKey' },
        Method = { ' 󰆧 ', 'LspKindMethod' },
        Module = { '  ', 'LspKindModule' },
        Namespace = { ' 󰌗 ', 'LspKindNamespace' },
        Number = { '  ', 'LspKindNumber' },
        Operator = { ' 󰆕 ', 'LspKindOperator' },
        Package = { '  ', 'LspKindPackage' },
        Property = { ' 󰜢 ', 'LspKindProperty' },
        Struct = { '  ', 'LspKindStruct' },
        TypeParameter = { ' 󰅲 ', 'LspKindTypeParameter' },
        Variable = { '  ', 'LspKindVariable' },
        Array = { ' 󰅪 ', 'LspKindArray' },
        Boolean = { '  ', 'LspKindBoolean' },
        Null = { ' 󰟢 ', 'LspKindNull' },
        Object = { ' 󰅩 ', 'LspKindObject' },
        String = { ' 󰉿 ', 'LspKindString' },
        TypeAlias = { '  ', 'LspKindTypeAlias' },
        Parameter = { '  ', 'LspKindParameter' },
        StaticMethod = { '  ', 'LspKindStaticMethod' },
        Macro = { '  ', 'LspKindMacro' },
        Text = { ' 󰉿 ', 'LspKindText' },
        Snippet = { '  ', 'LspKindSnippet' },
        Folder = { ' 󰉋 ', 'LspKindFolder' },
        Unit = { '  ', 'LspKindUnit' },
        Value = { ' 󰎠 ', 'LspKindValue' },
      },
    },
    scroll_preview = {
      scroll_down = '<C-d>',
      scroll_up = '<C-u>',
    },
    request_timeout = 3000,
  })
end
