return function()
  require('catppuccin').setup({
    flavour = 'mocha',
    background = { light = 'latte', dark = 'mocha' },
    dim_inactive = {
      enabled = false,
      shade = 'dark',
      percentage = 0.25,
    },
    transparent_background = false,
    show_end_of_buffer = false,
    term_colors = true,
    compile_path = vim.fn.stdpath('cache') .. '/catppuccin',
    styles = {
      comments = {},
      properties = {},
      functions = {},
      keywords = {},
      operators = {},
      conditionals = {},
      loops = {},
      booleans = {},
      numbers = {},
      types = {},
      strings = {},
      variables = {},
    },
    integrations = {
      aerial = false,
      alpha = false,
      barbar = false,
      barbecure = {
        dim_dirname = false,
        bold_basename = false,
        dim_context = false,
        alt_background = false,
      },
      beacon = false,
      coc_nvim = false,
      dashboard = false,
      dropbar = { 
        enabled = false,
        color_mode = false
      },
      fern = false,
      fidget = false,
      flash = false,
      gitsigns = true,
      harpoon = false,
      headlines = false,
      hop = true,
      indent_blankline = {
        enabled = true,
        scope_color = '',
        colored_indent_levels = false,
      },
      leap = false,
      lightspeed = false,
      lsp_saga = true,
      markdown = false,
      mini = {
        enabled = false,
        indentscope_color = '',
      },
      neotree = {
        enabled = false,
        show_root = true,
        transparent_panel = false
      },
      neogit = false,
      neotest = false,
      noice = false,
      NormalNvim = false,
      notifier = false,
      cmp = true,
      dap = false,
      dap_ui = false,
      native_lsp = {
        enabled = true,
        virtual_text = {
          errors = {},
          hints = {},
          warnings = {},
          information = {},
        },
        underlines = {
          errors = { 'underline' },
          hints = { 'underline' },
          warnings = { 'underline' },
          information = { 'underline' },
        },
        inlay_hints = {
          background = true,
        },
      },
      navic = {
        enabled = false
      },
      notify = true,
      semantic_tokens = false,
      nvimtree = true,
      treesitter_context = true,
      treesitter = true,
      ts_rainbow2 = false,
      ts_rainbow = true,
      ufo = false,
      window_picer = false,
      octo = false,
      overseer = false,
      pounce = false,
      rainbow_delimiters = false,
      symbols_outline = false,
      telekasten = false,
      telescope = {
        enabled = true,
        -- style = 'nvchad'
      },
      lsp_trouble = true,
      gitgutter = false,
      illuminate = {
        enabled = true,
        lsp = false,
      },
      sandwich = false,
      vim_sneak = false,
      vimwiki = false,
      which_key = true,
      mason = true,
    },
    color_overrides = {},
    highlight_overrides = {
      all = function(colors)
        return {
          Pmenu = { fg = colors.text, bg = colors.base },
          PmenuSel = { bg = colors.surface1 },
          PmenuBorder = { fg = colors.text, style = { 'bold' } },
          CmpItemAbbr = { fg = colors.text },
          CmpItemAbbrMatch = { fg = colors.text, style = { 'bold' } },
          CmpDoc = { fg = colors.text, style = { 'bold' } },
          CmpDocBorder = { fg = colors.text, style = { 'bold' } },
        }
      end,
    },
  })
  vim.api.nvim_command('colorscheme catppuccin')
end
