vim.keymap.set('i', 'jk', '<Esc>')
vim.keymap.set('n', '<C-h>', '<C-w>h', { desc = 'Go to left window', remap = true })
vim.keymap.set('n', '<C-j>', '<C-w>j', { desc = 'Go to lower window', remap = true })
vim.keymap.set('n', '<C-k>', '<C-w>k', { desc = 'Go to upper window', remap = true })
vim.keymap.set('n', '<C-l>', '<C-w>l', { desc = 'Go to right window', remap = true })
vim.keymap.set('n', '<A-[>', '<Cmd>vertical resize -5<CR>', { desc = 'Window Resize -5', remap = true })
vim.keymap.set('n', '<A-]>', '<Cmd>vertical resize +5<CR>', { desc = 'Window Resize +5', remap = true })
